fix: lint issues for bootprocess
browserstack/enigma pull request #170
Opened 2023-05-24 05:27 UTC by sharad-sharma

Should be merged together with https://github.com/browserstack/enigma-access-modules/pull/70

2023-05-24 10:06 UTC, vedharish requested changes

2023-05-24 10:47 UTC, sharad-sharma commented on bootprocess/tests/test_views_helper.py
> +            del user, status, group
Tried this way ```def filter(self, _, __, ___, is_owner=False):``` but it's not working for named arguments.

2023-05-24 10:48 UTC, sharad-sharma commented on pylama.ini
> +ignore = R0903
Sure, adding it for `*/tests/test_*`.

2023-05-25 13:15 UTC, sharad-sharma commented
lint is failing because of change in `emailSES` to `email_via_smtp` in `bootprocess.general`.
Should be passing for `fix_linter_issues_clone` branch of `enigma-access-modules`

2023-05-26 02:57 UTC, vedharish requested changes

2023-05-26 02:57 UTC, vedharish commented on Access/base_email_access/access.py
> +    def email_via_smtp(self, destination, subject, body):
Can we add a comment on why we have added it like this? `def email_via_smtp` calling helper method of same name - might be confusing in future

Also can we move it from bootprocess.general to `scripts/helpers` or `Access/helpers` - check within team what makes more sense - we will keep all global helper methods (like reading json from file etc) in the same file

2023-05-26 03:06 UTC, vedharish requested changes
Also celery pod is getting some issues on these branches

2023-05-29 11:33 UTC, sharad-sharma commented
> Also celery pod is getting some issues on these branches

Fixed the issues by merging from main

2023-06-01 10:34 UTC, vedharish approved these changes

2023-06-01 10:34 UTC, merged