feat: added integration to the pending UI with backend
browserstack/enigma pull request #214
Opened 2023-06-19 12:26 UTC by niveshm

2023-06-19 14:09 UTC, vedharish requested changes

2023-06-19 14:09 UTC, vedharish commented on Access/helpers.py
> +    return None
```suggestion
    return None
```
```suggestion
    return False
```

2023-06-20 16:43 UTC, niveshm commented on Access/helpers.py
> +    if days >= 1:
Yeah move the SLA to config

2023-06-22 15:16 UTC, vedharish submitted a review, later dismissed

2023-06-23 12:33 UTC, sharad-sharma approved these changes

2023-06-23 12:36 UTC, merged